#springboot2.X
server:
  port: 8084
  servlet:
     context-path: /dubbo-provider
spring:
  datasource:
    username: aml
    password: aml
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000