#springboot2.X
server:
  port: 8081
  servlet:
     context-path: /SpringBootDay01
spring:
  datasource:
    username: aml
    password: aml
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
 
mybatis:
  mapper-locations: classpath:com/zyd/mapper/*Mapper.xml
  configuration: 
       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#showSql
logging:
  level:
    com.zyd.dao: debug